# -*- coding: utf-8 -*-
"""alert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oVwXwfcEOlFOGEeajRbK-X7nAbyHIQHw
"""

def alert(animal_found):
    if animal_found:
        print("⚠️ Animal detected! Do NOT start vehicle.")
    else:
        print("✅ Safe to start vehicle.")