# -*- coding: utf-8 -*-
"""detect.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pb6YYOJyeOzG_J4ePpeambndfKguK5Z5
"""

from ultralytics import YOLO

def load_model():
    return YOLO("yolov8n.pt")

def detect(image_path):
    model = load_model()
    results = model(image_path)
    return results

